export const items = [
  {
    image: 'https://i.postimg.cc/cLyNFxjW/1.png',
    brand: 'Coffee Shop Selections',
    price: 950,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/zBBmyVLC/2.png',
    brand: 'Coffee Shop Selections',
    price: 950,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Qtn21h5R/3.png',
    brand: 'Coffee Shop Selections',
    price: 950,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/0NZR5pN5/4.png',
    brand: 'Coffee Shop Selections',
    price: 950,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/FHswWYZ2/1.png',
    brand: 'Costa',
    price: 1100,
    system: 'Tassimo',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/SKn34HHd/2.png',
    brand: 'Costa',
    price: 1100,
    system: 'Tassimo',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/zf4MG0rr/3.png',
    brand: 'Costa',
    price: 1100,
    system: 'Tassimo',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/qRnFhyJC/4.png',
    brand: 'Costa',
    price: 1100,
    system: 'Tassimo',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/R0JsyKnb/1.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mkBmPnp0/2.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/63sjXqr6/3.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/DyfCFtXG/4.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/4yPBV1rn/5.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xj3sw0cY/6.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/m2dmr8Y5/7.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/sXpnDzmY/8.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/13fJVwM5/9.png',
    brand: 'Gevalia',
    price: 960,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/sDZMB27C/1.png',
    brand: 'Jacobs',
    price: 680,
    system: 'Tassimo',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/wj87DdQy/2.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/1zyXYcTy/3.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/gJT0j900/4.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/4x6n5FW8/5.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/d3ZVTW7j/6.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nzzznVp5/7.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KYQjX3SB/8.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/dDMtR8rP/9.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PrZ1gy6D/10.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/GmxG22nh/11.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/pdV8nHPQ/12.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/j2fJrqhT/13.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/G2Hyqx8H/14.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/9MKqSwZ1/15.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Cx7n0QbR/16.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nc8DG7Hh/17.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/MH1XFPWK/18.png',
    brand: 'Jacobs',
    price: 910,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PfDLJxms/19.png',
    brand: 'Jacobs',
    price: 1250,
    system: 'Tassimo',
    pods: 24,
  },
  {
    image: 'https://i.postimg.cc/bJyLC68y/1.png',
    brand: 'Kenco',
    price: 750,
    system: 'Tassimo',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/Y0jRkhhT/2.png',
    brand: 'Kenco',
    price: 1150,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/k4TskxXx/3.png',
    brand: 'Kenco',
    price: 1150,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/RC3pjDKh/1.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/W175GLLW/2.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/bYKV899T/3.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/5tNnp7fx/4.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/y8Kf3653/5.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nzXTfXsg/6.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/25cTtQ5n/7.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTMxdNsS/8.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/26gGkCh6/10.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/X7fLWSJj/11.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PJZ4N0QM/12.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/pVnk0nMn/14.png',
    brand: "L'OR",
    price: 840,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/m2fjK2Tp/15.png',
    brand: "L'OR",
    price: 980,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xdC3LXP8/16.png',
    brand: "L'OR",
    price: 1060,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/d0xm6JWB/17.png',
    brand: "L'OR",
    price: 1060,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/9QcpF8RG/18.png',
    brand: "L'OR",
    price: 1060,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/P5KMLWY0/19.png',
    brand: "L'OR",
    price: 1220,
    system: 'Tassimo',
    pods: 24,
  },
  {
    image: 'https://i.postimg.cc/fLS7g1ph/20.png',
    brand: "L'OR",
    price: 1220,
    system: 'Tassimo',
    pods: 24,
  },
  {
    image: 'https://i.postimg.cc/sxsPKzQH/1.png',
    brand: 'Marcilla',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/VvgqVhXf/2.png',
    brand: 'Marcilla',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PrfzwtkP/3.png',
    brand: 'Marcilla',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/9XYY0DK6/4.png',
    brand: 'Marcilla',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTsGGW0g/5.png',
    brand: 'Marcilla',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/4dJbQZhL/1.png',
    brand: 'Tassimo',
    price: 950,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/NGC7m3GD/2.png',
    brand: 'Tassimo',
    price: 950,
    system: 'Tassimo',
    pods: 21,
  },
  {
    image: 'https://i.postimg.cc/vB37PjrQ/3.png',
    brand: 'Tassimo',
    price: 950,
    system: 'Tassimo',
    pods: 21,
  },
  {
    image: 'https://i.postimg.cc/WzyGVkYC/4.png',
    brand: 'Tassimo',
    price: 950,
    system: 'Tassimo',
    pods: 21,
  },
  {
    image: 'https://i.postimg.cc/HxhzYRV6/1.png',
    brand: "Bailey's",
    price: 930,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTr7LN1t/2.png',
    brand: 'Cadbury',
    price: 930,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/5yzRZbnB/3.png',
    brand: 'Café Hag',
    price: 930,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/HW8RJ9dr/4.png',
    brand: 'Friele',
    price: 850,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/8CCnThZP/5.png',
    brand: 'Grand Mere',
    price: 720,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/q7ZDqzFc/6.png',
    brand: 'Grand Mere',
    price: 720,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/vZbNNR9n/7.png',
    brand: 'Milka',
    price: 970,
    system: 'Tassimo',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/JnD6kRwf/8.png',
    brand: 'Milka',
    price: 970,
    system: 'Tassimo',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/qRPmcW4z/9.png',
    brand: 'Tea Time',
    price: 930,
    system: 'Tassimo',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/jqXTqhXy/1.png',
    brand: 'Mix + Šolja',
    price: 5690,
    system: 'Tassimo',
    pods: 80,
  },
  {
    image: 'https://i.postimg.cc/gk2Wx6SQ/2.png',
    brand: 'Mix + Šolja',
    price: 7100,
    system: 'Tassimo',
    pods: 109,
  },
  {
    image: 'https://i.postimg.cc/s2cTv8Xk/1.png',
    brand: 'Belmio',
    price: 780,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Pfc2p1X5/2.png',
    brand: 'Belmio',
    price: 780,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KjdN6hqM/3.png',
    brand: 'Belmio',
    price: 780,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PrwKmNJz/4.png',
    brand: 'Belmio',
    price: 780,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/VvSgZkRw/5.png',
    brand: 'Belmio',
    price: 780,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/ZK3NQ91f/1.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/zfdHhTgf/2.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/VLyrXfdX/3.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mrZFhmhq/4.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/W1wk2Bpg/5.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/C1zBsdGs/6.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/brnZ4MFG/7.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/B6k8YsN9/8.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/v8xx1gHQ/9.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/8z478Lwb/10.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/d1k3TpFW/11.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/7LQbhDFG/12.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/rmBmGjFq/13.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/QN7V820C/14.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/5NMy6sR3/15.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/524tm61Q/16.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/yYXd9Fqz/17.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/VNTL1gtX/18.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/gc3kFv26/19.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3NjKXHcZ/20.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/NjjgHS71/21.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mgpTNj8K/22.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/tC5q7pPq/23.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nL6ZNz8k/24.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nLspdmWr/25.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/x182CHn5/26.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/vZKd6Bms/27.png',
    brand: 'Café René',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KYdfLXLj/1.png',
    brand: 'Café Royal',
    price: 790,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KvJ5f3Ld/2.png',
    brand: 'Café Royal',
    price: 790,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/dV3jxQjD/3.png',
    brand: 'Café Royal',
    price: 790,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/1zNcyWTQ/4.png',
    brand: 'Café Royal',
    price: 790,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Z5NCR1TV/1.png',
    brand: 'Dolce Vita',
    price: 470,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/Ss1yVrSn/2.png',
    brand: 'Dolce Vita',
    price: 470,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/N0Yf0FCj/3.png',
    brand: 'Dolce Vita',
    price: 470,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/jjXqnTBQ/4.png',
    brand: 'Dolce Vita',
    price: 470,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/FRHrjq4t/5.png',
    brand: 'Dolce Vita',
    price: 470,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/xTz0yMWd/6.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/g2ym1dcF/7.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/5yZfW2F1/8.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3r68vnf6/9.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/XNTZbjWp/10.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/DyLSf9f5/11.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/q7bRZ0QB/12.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/XJtv48TT/13.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTDdZ6Gm/14.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/c18HTp3Z/15.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/W1s1NtHb/16.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTvdVLg4/17.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/d01QCpFb/18.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/6349jZyz/19.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nLPFG2cC/20.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/9FYcnCQ3/21.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/2ypCP5WY/22.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/yYHVjkBX/23.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/HkWTGRrr/24.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/T2mdnr83/25.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Xvp3q5c3/26.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/vZPbGhn3/27.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/76zkMyWW/28.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/kGddTprX/29.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/BZx3j4D8/30.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PJzn9Qhb/31.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/xTn2Hhy6/32.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/kXsdysTq/33.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/2S5N9Wtv/34.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Mpr2CTkL/35.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/G2GWTxB0/36.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Znm18v3W/37.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/NFxZpG7p/38.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/CLF3dDSt/39.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/PfzGtKsY/40.png',
    brand: 'Dolce Vita',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/7ZJ2pKfr/1.png',
    brand: 'Foodness',
    price: 830,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/TPrWPhVk/2.png',
    brand: 'Foodness',
    price: 830,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/fb49ZY9t/3.png',
    brand: 'Foodness',
    price: 830,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/G2dTTrzb/4.png',
    brand: 'Foodness',
    price: 830,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/hj2vJmf0/1.png',
    brand: 'Galaxy',
    price: 770,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/Zn0R6qNz/2.png',
    brand: 'Galaxy',
    price: 770,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/mZ6hBQxL/3.png',
    brand: 'Galaxy',
    price: 770,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/FzqKpQbd/4.png',
    brand: 'Galaxy',
    price: 770,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/hjDhPsPj/5.png',
    brand: 'Galaxy',
    price: 770,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/7Y0C9fcq/1.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mgSPxKBq/2.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/QtFCTt1G/3.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/MGPXHRcm/4.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3RzRCTFy/5.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/hGPfKMGG/6.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/1RN4R8yD/7.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/65Jq8BQg/8.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/D0szxMxx/9.png',
    brand: 'Gimoka',
    price: 710,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/qvKG8JcK/1.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/j2CHCtdL/2.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/SQtL32D8/3.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/cCjQn2rT/4.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/BvgHgXjj/5.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/MKM0S6FL/6.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/sDkYDFFg/7.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/9fVyZGQ3/8.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/fRYxVHZj/9.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/gJ2RBmhN/10.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/ZqVvN2Q3/11.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/DyXGNCWk/12.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mrbFtBmB/13.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Hn7rfxk4/14.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3RN4F9Mq/15.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/BnfFfxD8/16.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/XXSr3bZM/17.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mDncXMBg/18.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/c1KTsBKT/19.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/XNTLXBdW/20.png',
    brand: 'Kaffekapslen',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/q7bXrN49/21.png',
    brand: 'Kaffekapslen',
    price: 1060,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/rwT9N6fY/22.png',
    brand: 'Kaffekapslen',
    price: 1060,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/jSh4889q/23.png',
    brand: 'Kaffekapslen',
    price: 3280,
    system: 'Dolce Gusto',
    pods: 80,
  },
  {
    image: 'https://i.postimg.cc/W3xGDxD8/24.png',
    brand: 'Kaffekapslen',
    price: 3280,
    system: 'Dolce Gusto',
    pods: 80,
  },
  {
    image: 'https://i.postimg.cc/mDP3gTrh/25.png',
    brand: 'Kaffekapslen',
    price: 3280,
    system: 'Dolce Gusto',
    pods: 80,
  },
  {
    image: 'https://i.postimg.cc/qMVFS5m2/1.png',
    brand: 'Lavazza',
    price: 850,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KvPW2DVw/2.png',
    brand: 'Lavazza',
    price: 850,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/wjFbtT9k/3.png',
    brand: 'Lavazza',
    price: 850,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/nhnPcQfz/4.png',
    brand: 'Lavazza',
    price: 850,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/VLZC533C/1.png',
    brand: 'Segafredo',
    price: 620,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/L8qZPxp0/2.png',
    brand: 'Segafredo',
    price: 620,
    system: 'Dolce Gusto',
    pods: 10,
  },
  {
    image: 'https://i.postimg.cc/8cP7zH44/3.png',
    brand: 'Drink me Chai',
    price: 650,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/zBNL95R9/4.png',
    brand: 'Twix',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/QxCBLfHx/5.png',
    brand: 'Bounty',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/d197FX2D/6.png',
    brand: 'Maltesers',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/9QvwYyXX/7.png',
    brand: 'Mars',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/jqZWkpqF/8.png',
    brand: 'Milky Way',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/j2gLw7kb/9.png',
    brand: 'Snickers',
    price: 720,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/vZ6cTDrJ/10.png',
    brand: 'Celebrations',
    price: 760,
    system: 'Dolce Gusto',
    pods: 8,
  },
  {
    image: 'https://i.postimg.cc/BbKxx3Rb/1.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/637RXwWc/2.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/d0NdpDYD/3.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/Dwg1QBpr/4.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/vH5rTQWS/5.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/K8Fngdfc/6.png',
    brand: 'Nescafé',
    price: 800,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/L4YBdkhS/7.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/0NyDVDhL/8.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/jqp6RWJ7/9.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/QtR7NPV3/10.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Zqnv8Zdm/11.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/qvjC6ggQ/12.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/CK2BJtGq/13.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/FsbSmT4M/14.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/SR6nSxw6/15.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/wj6mBDx7/16.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/QCGBZTnN/17.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/W3JDyn8f/18.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/KvbK9tMJ/19.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/T37pYSH4/20.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/MpTp45Kb/21.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/43HN43cY/22.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Vsqvb5VM/23.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/0QpkmHcx/24.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/XYzY05rM/25.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/zXpf065G/26.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/15yt0Pkd/27.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/J05hwdkK/28.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Bb4qCcVF/29.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/hjF4Xq8p/30.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/yYfVFRXJ/31.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/656W2cRJ/32.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/ZRhZTxZQ/33.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/mDN4h1gg/34.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/6QZtJmsR/35.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/66f6pg8f/36.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/rwKqgpQf/37.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/HkRdNCNd/38.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/7P9DkzRB/39.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/T1tXJ8m8/40.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/LXTdmdxq/41.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/L6hdFbLX/42.png',
    brand: 'Nescafé',
    price: 880,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3w25b0pF/43.png',
    brand: 'Nescafé',
    price: 890,
    system: 'Dolce Gusto',
    pods: 18,
  },
  {
    image: 'https://i.postimg.cc/KzFSXcDS/44.png',
    brand: 'Nescafé',
    price: 890,
    system: 'Dolce Gusto',
    pods: 18,
  },
  {
    image: 'https://i.postimg.cc/wMTCvWrw/45.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/D0jtbrkn/46.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/YC5B3z4S/47.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/nhjtBPh5/48.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/sDLkj44J/49.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/9XL3Sh4K/50.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/mkDnRPcq/51.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/RhDD0vK0/52.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/mrypHYCJ/53.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/RVWYDnxJ/54.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/X7tPS7nH/55.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/DfjD6PHK/56.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/NjTzgqMg/57.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/MGSrHPM1/58.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/HxWZ4rtx/59.png',
    brand: 'Nescafé',
    price: 1400,
    system: 'Dolce Gusto',
    pods: 30,
  },
  {
    image: 'https://i.postimg.cc/50TfhWyw/1.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/JhhmtzBN/2.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/3xY35B8b/3.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/jjkTfYzG/4.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/bwgpztdY/5.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/NG2s1FCb/6.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/4d7gb2Pn/7.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/JnfWT3Yx/8.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/vHWGNjsV/9.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/8cLgxFqS/10.png',
    brand: 'Senso Nocturno',
    price: 650,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/Y06Tb5W2/1.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/QxqR5rD0/2.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/MZ1k6QFk/3.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/JnJFzfK3/4.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/kXC0Bg02/5.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/CxL9s6LY/6.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/5tDG145N/7.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/13C2CcfF/8.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/bvZMKDtB/9.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/c1RjyNv0/10.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/hPKYK3mx/11.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/tCDMJtdc/12.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/g2JBZXN2/13.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/zGc2SzcS/14.png',
    brand: 'Starbucks',
    price: 790,
    system: 'Dolce Gusto',
    pods: 12,
  },
  {
    image: 'https://i.postimg.cc/3NFbg2sd/1.png',
    brand: 'Tonino Lamborghini',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/QtL6w6sF/2.png',
    brand: 'Tonino Lamborghini',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/hvc2PfXg/3.png',
    brand: 'Tonino Lamborghini',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/LsgCyddd/4.png',
    brand: 'Tonino Lamborghini',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/fLxHNxTB/5.png',
    brand: 'Tonino Lamborghini',
    price: 750,
    system: 'Dolce Gusto',
    pods: 16,
  },
  {
    image: 'https://i.postimg.cc/0N3QswHM/1.png',
    brand: 'Kaffekapslen',
    price: 2600,
    system: 'Dolce Gusto',
    pods: 64,
  },
  {
    image: 'https://i.postimg.cc/mkWgcG4T/2.png',
    brand: 'Nescafé',
    price: 5000,
    system: 'Dolce Gusto',
    pods: 96,
  },
  {
    image: 'https://i.postimg.cc/LX1s68ry/3.png',
    brand: 'Nescafé',
    price: 5000,
    system: 'Dolce Gusto',
    pods: 96,
  },
  {
    image: 'https://i.postimg.cc/y60NMWhx/4.png',
    brand: 'Kaffekapslen + Descaler',
    price: 5300,
    system: 'Dolce Gusto',
    pods: 128,
  },
  {
    image: 'https://i.postimg.cc/0N3QswHM/1.png',
    brand: 'Mix',
    price: 7500,
    system: 'Dolce Gusto',
    pods: 160,
  },
];
